---
- name: Install DuckDNS background service
  package:
    name: jzelinskie/duckdns/duckdns
    state: present
  when: ansible_os_family == "Darwin" and duckdns_subdomain != "" and duckdns_token != ""

- name: Configure DuckDNS background service
  template:
    src: duckdns.conf.j2
    dest: $HOME/.duckdns
  when: ansible_os_family == "Darwin" and duckdns_subdomain != "" and duckdns_token != ""

- name: Set up DuckDNS LaunchAgent
  command: ln -sfv /usr/local/opt/duckdns/*.plist ~/Library/LaunchAgents
  when: ansible_os_family == "Darwin" and duckdns_subdomain != "" and duckdns_token != ""

- name: Run DuckDNS LaunchAgent
  command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.duckdns.plist
  when: ansible_os_family == "Darwin" and duckdns_subdomain != "" and duckdns_token != ""
