---
- name: Install DuckDNS background service via Homebrew
  package:
    name: jzelinskie/duckdns/duckdns
    state: present
  when: ansible_os_family == "Darwin" and duckdns_subdomain != "" and duckdns_token != ""

- name: Configure DuckDNS background service
  template:
    src: duckdns.conf.j2
    dest: $HOME/.duckdns
  when: ansible_os_family == "Darwin" and duckdns_subdomain != "" and duckdns_token != ""

- name: Run DuckDNS background service at login
  command: brew services start duckdns
  when: ansible_os_family == "Darwin" and duckdns_subdomain != "" and duckdns_token != ""
